import{openPdf,renderPage}from'./pdfViewer.js';import{ocrCanvas}from'./ocr.js';import{readDocx}from'./docReader.js';import{analyse}from'../patterns/index.js';import{textMatchBox,ipaLabelBoxes}from'./geometry.js';
const byId=id=>document.getElementById(id),need=id=>{const el=byId(id);if(!el)throw new Error(`Missing HTML element: ${id}`);return el};
const ui={drop:need('dropZone'),file:need('fileInput'),choose:need('chooseBtn'),selected:need('selectedFile'),scan:need('scanBtn'),prev:need('prevFindingBtn'),next:need('nextFindingBtn'),clear:need('clearManualBtn'),csv:need('csvBtn'),export:need('exportBtn'),ocrAll:need('ocrAll'),names:need('detectNames'),ipa:need('ipaMode'),progressWrap:need('progressWrap'),progress:need('progressBar'),progressText:need('progressText'),status:need('statusText'),summary:need('summary'),filter:need('filterInput'),list:need('findingsList'),count:need('findingCount'),viewer:need('documentViewer'),indicator:need('pageIndicator')};
const state={file:null,kind:null,pdf:null,pages:[],findings:[],docxHtml:'',activeId:null,observer:null,drag:null,suppressClick:false};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function progress(value,message){ui.progressWrap.hidden=false;ui.progress.value=value;ui.progressText.textContent=`${Math.round(value)}%`;ui.status.textContent=message}
function setFile(file){if(!file||!/\.(pdf|docx|txt)$/i.test(file.name)){ui.selected.textContent='Choose a PDF, DOCX or TXT file.';return}state.file=file;state.kind=file.name.split('.').pop().toLowerCase();ui.selected.textContent=file.name;ui.scan.disabled=false}
function addFinding(f){f.id=state.findings.length+1;state.findings.push(f)}
function updateSummary(){const values=[['Pages',state.pages.length||(state.kind==='docx'?1:0)],['Findings',state.findings.length],['Selected',state.findings.filter(f=>f.use).length],['Manual boxes',state.findings.filter(f=>f.manual).length]];ui.summary.innerHTML=values.map(([label,n])=>`<div class="metric"><strong>${n}</strong><span>${label}</span></div>`).join('')}
async function scan(){state.pages=[];state.findings=[];state.pdf=null;state.docxHtml='';state.activeId=null;ui.scan.disabled=true;for(const b of[ui.export,ui.csv,ui.prev,ui.next,ui.clear])b.disabled=true;ui.viewer.innerHTML='<div class="empty">Processing…</div>';try{if(state.kind==='pdf')await scanPdf();else if(state.kind==='docx')await scanDocx();else await scanText();renderFindings();updateSummary();ui.csv.disabled=!state.findings.length;ui.prev.disabled=!state.findings.length;ui.next.disabled=!state.findings.length;progress(100,'Scan complete')}catch(error){console.error(error);ui.viewer.innerHTML=`<div class="empty">${esc(error.message)}</div>`;alert(`Processing failed: ${error.message}`)}finally{ui.scan.disabled=false}}
async function scanPdf(){state.pdf=await openPdf(state.file);for(let n=1;n<=state.pdf.numPages;n++){progress((n-1)/state.pdf.numPages*100,`Reading page ${n} of ${state.pdf.numPages}`);const page=await renderPage(state.pdf,n,1.7);let text=page.text,items=[...page.items],source='PDF text';if(ui.ocrAll.checked||text.replace(/\s/g,'').length<35){const ocr=await ocrCanvas(page.canvas,p=>progress(((n-1)+p/100)/state.pdf.numPages*100,`OCR page ${n}`));text+='\n'+ocr.text;items.push(...ocr.items);source='OCR + PDF text'}const findings=analyse(text,ui.names.checked,source);for(const f of findings){f.box=textMatchBox(items,f.value);addFinding({...f,page:n,use:!!f.box,manual:false})}if(ui.ipa.checked)for(const f of ipaLabelBoxes(items,page.width,page.height))addFinding({...f,page:n,use:true,manual:false});state.pages.push({...page,items,number:n})}buildPdfViewer();ui.export.disabled=false;ui.clear.disabled=false}
async function scanDocx(){progress(20,'Reading DOCX');const doc=await readDocx(state.file);state.docxHtml=doc.html;for(const f of analyse(doc.text,ui.names.checked,'DOCX text'))addFinding({...f,page:1,use:true,manual:false});buildDocxViewer();ui.export.disabled=false}
async function scanText(){progress(30,'Reading TXT');for(const f of analyse(await state.file.text(),ui.names.checked,'Text file'))addFinding({...f,page:'',use:true,manual:false});ui.viewer.innerHTML='<div class="empty">TXT files provide findings only.</div>';ui.indicator.textContent='TXT findings'}
function buildPdfViewer(){state.observer?.disconnect();ui.viewer.innerHTML='';for(const p of state.pages){const el=document.createElement('section');el.className='pdf-page';el.id=`page-${p.number}`;el.dataset.page=p.number;el.append(p.canvas);const o=document.createElement('canvas');o.className='redaction-layer';o.width=p.width;o.height=p.height;o.dataset.page=p.number;el.append(o);const label=document.createElement('span');label.className='page-label';label.textContent=`Page ${p.number}`;el.append(label);ui.viewer.append(el);bindOverlay(o);drawOverlay(o)}state.observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)ui.indicator.textContent=`Page ${visible.target.dataset.page} / ${state.pages.length}`},{root:ui.viewer,threshold:[.2,.5,.8]});document.querySelectorAll('.pdf-page').forEach(p=>state.observer.observe(p))}
function bindOverlay(canvas){canvas.onpointerdown=e=>{const r=canvas.getBoundingClientRect(),sx=canvas.width/r.width,sy=canvas.height/r.height,x=(e.clientX-r.left)*sx,y=(e.clientY-r.top)*sy;state.drag={canvas,x,y,w:0,h:0};canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(state.drag?.canvas!==canvas)return;const r=canvas.getBoundingClientRect();state.drag.w=(e.clientX-r.left)*canvas.width/r.width-state.drag.x;state.drag.h=(e.clientY-r.top)*canvas.height/r.height-state.drag.y;drawOverlay(canvas)};canvas.onpointerup=()=>{if(state.drag?.canvas!==canvas)return;const d=state.drag;state.drag=null;if(Math.abs(d.w)>8&&Math.abs(d.h)>8){state.suppressClick=true;addFinding({page:+canvas.dataset.page,type:'Manual redaction',value:'User-selected area',context:'Manual box',source:'manual',use:true,manual:true,box:{x:Math.min(d.x,d.x+d.w),y:Math.min(d.y,d.y+d.h),w:Math.abs(d.w),h:Math.abs(d.h)}});renderFindings();updateSummary()}drawOverlay(canvas)};canvas.onclick=e=>{if(state.suppressClick){state.suppressClick=false;return}const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height,page=+canvas.dataset.page,hit=[...state.findings].reverse().find(f=>f.page===page&&f.box&&x>=f.box.x&&x<=f.box.x+f.box.w&&y>=f.box.y&&y<=f.box.y+f.box.h);if(hit){hit.use=!hit.use;drawOverlay(canvas);renderFindings();updateSummary()}}}
function drawOverlay(canvas){const ctx=canvas.getContext('2d'),page=+canvas.dataset.page;ctx.clearRect(0,0,canvas.width,canvas.height);for(const f of state.findings.filter(f=>f.page===page&&f.box)){ctx.fillStyle=f.use?'rgba(180,35,24,.38)':'rgba(21,94,239,.16)';ctx.strokeStyle=f.use?'#b42318':'#155eef';ctx.lineWidth=2;ctx.fillRect(f.box.x,f.box.y,f.box.w,f.box.h);ctx.strokeRect(f.box.x,f.box.y,f.box.w,f.box.h)}if(state.drag?.canvas===canvas){ctx.strokeStyle='#111';ctx.setLineDash([8,5]);ctx.strokeRect(state.drag.x,state.drag.y,state.drag.w,state.drag.h);ctx.setLineDash([])}}
function buildDocxViewer(){ui.viewer.innerHTML=`<article id="docxPreview" class="docx-page">${state.docxHtml}</article>`;applyDocx();ui.indicator.textContent='DOCX preview'}
function applyDocx(){const root=byId('docxPreview');if(!root)return;root.innerHTML=state.docxHtml;const selected=state.findings.filter(f=>f.use&&f.value.length>1&&!f.value.startsWith('Value near ')).sort((a,b)=>b.value.length-a.value.length),walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){let parts=[{text:node.nodeValue,redact:false}];for(const f of selected){const needle=f.value.toLowerCase();parts=parts.flatMap(p=>{if(p.redact)return[p];const out=[],source=p.text,lower=source.toLowerCase();let pos=0,i;while((i=lower.indexOf(needle,pos))>=0){if(i>pos)out.push({text:source.slice(pos,i),redact:false});out.push({text:source.slice(i,i+needle.length),redact:true});pos=i+needle.length}if(pos<source.length)out.push({text:source.slice(pos),redact:false});return out.length?out:[p]})}if(parts.some(p=>p.redact)){const frag=document.createDocumentFragment();for(const p of parts){if(p.redact){const span=document.createElement('span');span.className='docx-redaction';span.textContent=p.text;frag.append(span)}else frag.append(document.createTextNode(p.text))}node.replaceWith(frag)}}}
function renderFindings(){const q=ui.filter.value.toLowerCase(),shown=state.findings.filter(f=>`${f.type} ${f.value} ${f.context}`.toLowerCase().includes(q));ui.count.textContent=shown.length;ui.list.innerHTML=shown.length?shown.map(f=>`<div class="finding ${state.activeId===f.id?'active':''}" data-id="${f.id}"><input class="finding-check" type="checkbox" ${f.use?'checked':''}><div><strong>${esc(f.type)}</strong><span>${esc(f.value)}</span><small>Page ${f.page||'—'} · ${esc(f.source)}</small></div></div>`).join(''):'<p class="muted">No matching findings.</p>';document.querySelectorAll('.finding').forEach(row=>{const id=+row.dataset.id,f=state.findings.find(x=>x.id===id),check=row.querySelector('.finding-check');check.onchange=e=>{e.stopPropagation();f.use=check.checked;state.kind==='docx'?applyDocx():document.querySelectorAll('.redaction-layer').forEach(drawOverlay);updateSummary()};row.onclick=e=>{if(e.target!==check)jump(id)}})}
function jump(id){const f=state.findings.find(x=>x.id===id);if(!f)return;state.activeId=id;if(state.kind==='pdf'&&f.page)byId(`page-${f.page}`)?.scrollIntoView({behavior:'smooth',block:'center'});else byId('docxPreview')?.scrollIntoView({behavior:'smooth',block:'start'});renderFindings()}
function step(direction){if(!state.findings.length)return;let i=state.findings.findIndex(f=>f.id===state.activeId);i=(i+direction+state.findings.length)%state.findings.length;jump(state.findings[i].id)}
function clearManual(){state.findings=state.findings.filter(f=>!f.manual);document.querySelectorAll('.redaction-layer').forEach(drawOverlay);renderFindings();updateSummary()}
async function exportRedacted(){try{if(state.kind==='pdf')await exportPdf();else if(state.kind==='docx')await exportDocx()}catch(error){console.error(error);alert(`Export failed: ${error.message}`)}}
async function exportPdf(){const doc=await window.PDFLib.PDFDocument.create();for(let n=1;n<=state.pdf.numPages;n++){progress((n-1)/state.pdf.numPages*95,`Building export page ${n}`);const source=state.pages[n-1],page=await renderPage(state.pdf,n,2),ratio=page.scale/source.scale,ctx=page.canvas.getContext('2d');ctx.fillStyle='#000';for(const f of state.findings.filter(f=>f.page===n&&f.use&&f.box))ctx.fillRect(f.box.x*ratio,f.box.y*ratio,f.box.w*ratio,f.box.h*ratio);const image=await doc.embedPng(await canvasBuffer(page.canvas)),pdfPage=doc.addPage([page.width,page.height]);pdfPage.drawImage(image,{x:0,y:0,width:page.width,height:page.height})}download(await doc.save(),state.file.name.replace(/\.pdf$/i,'')+'-REDACTED.pdf','application/pdf');progress(100,'Redacted PDF downloaded')}
async function exportDocx(){if(!window.html2canvas)throw new Error('DOCX export library did not load.');applyDocx();const capture=await window.html2canvas(need('docxPreview'),{scale:2,backgroundColor:'#fff',useCORS:true,logging:false});if(!capture.width||!capture.height)throw new Error('DOCX preview is empty.');const doc=await window.PDFLib.PDFDocument.create(),pageW=1240,pageH=1754,chunk=Math.floor(capture.width*pageH/pageW);for(let y=0;y<capture.height;y+=chunk){const slice=document.createElement('canvas');slice.width=capture.width;slice.height=Math.min(chunk,capture.height-y);slice.getContext('2d').drawImage(capture,0,y,capture.width,slice.height,0,0,capture.width,slice.height);const image=await doc.embedPng(await canvasBuffer(slice)),height=pageW*slice.height/slice.width,page=doc.addPage([pageW,height]);page.drawImage(image,{x:0,y:0,width:pageW,height})}download(await doc.save(),state.file.name.replace(/\.docx$/i,'')+'-REDACTED.pdf','application/pdf');progress(100,'Redacted DOCX preview downloaded as PDF')}
function canvasBuffer(canvas){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?blob.arrayBuffer().then(resolve):reject(new Error('Canvas image generation failed.')),'image/png'))}
function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function exportCsv(){const safe=v=>{const s=String(v??'');return/^[=+@]/.test(s)?`'${s}`:s},quote=v=>`"${safe(v).replace(/"/g,'""')}"`,rows=[['Page','Type','Value','Context','Source','Selected'],...state.findings.map(f=>[f.page,f.type,f.value,f.context,f.source,f.use])];download('\ufeff'+rows.map(r=>r.map(quote).join(',')).join('\r\n'),'ipa-redaction-findings.csv','text/csv;charset=utf-8')}
ui.choose.onclick=()=>ui.file.click();ui.file.onchange=e=>setFile(e.target.files[0]);ui.scan.onclick=scan;ui.prev.onclick=()=>step(-1);ui.next.onclick=()=>step(1);ui.clear.onclick=clearManual;ui.csv.onclick=exportCsv;ui.export.onclick=exportRedacted;ui.filter.oninput=renderFindings;for(const name of['dragenter','dragover'])ui.drop.addEventListener(name,e=>{e.preventDefault();ui.drop.classList.add('drag')});for(const name of['dragleave','drop'])ui.drop.addEventListener(name,e=>{e.preventDefault();ui.drop.classList.remove('drag')});ui.drop.ondrop=e=>setFile(e.dataTransfer.files[0]);document.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement)return;if(e.key.toLowerCase()==='n')step(1);if(e.key.toLowerCase()==='p')step(-1)});
